steps:
  - name: node:16
    entrypoint: npm
    args: ['install']
  - name: node:16
    entrypoint: npm
    args: ['run', 'create-env']
    env:
      - 'NODE_ENV=${_NODE_ENV}'
      - 'DATABASE_URL=${_DATABASE_URL}'
      - 'JWT_SECRET=${_JWT_SECRET}'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
timeout: '1600s'
